### PR TITLE
138 req i7  relevant  exceptions

### LINKED ISSUE #138: REQ I.7
The system provides relevant explanations to failures/successes.
This including: DB failures, payment/supply failure, etc.

### PR DESCRIPTION
**Pull request by odedgal67**

### CODE REVIEW

File: dev/src/test/UnitTests/PurchaseTest.java [hunk 1]
```diff
@@ -68,31 +68,12 @@ void ifPaymentFailsAbortSupply() {
...
-        {
-            Assertions.fail();
-        }
     }
 
     @Test
     void ifSupplymentFailsAbortPayment() {
         Purchase subject = new Purchase(mockPaymentInformation, mockSupplyingInformation, mockuser, mockCart, mockPayment,mockSupplyer);
         when(mockSupplyer.supply(any(SupplyingInformation.class), any(HashMap.class))).thenReturn(false);
         Assertions.assertThrows(Exception.class, subject::executePurchase);
```
Comment (IlayGo97) [inline dev/src/test/UnitTests/PurchaseTest.java:90]: no aborts should happen?

**Review by IlayGo97 — APPROVED** [review]
Nice!
